apiVersion: management.project-flotta.io/v1alpha1
kind: EdgeWorkload
metadata:
  name: edge-ic-workload
  namespace: default
  annotations:
    podman/run.oci.keep_original_groups: "1"
spec:
  deviceSelector:
    matchLabels:
      app: camera
  data:
    egress:
      - source: images
        target: images
  type: pod
  pod:
    spec:
      containers:
        - name: edge-ic-workload
          image: quay.io/dpshekhawat/img-class:latest
          volumeMounts:
          - mountPath: /dev/video0
            name: video
          securityContext:
            seLinuxOptions:
              type: 'spc_t'
      restartPolicy: Always
      volumes:
      - name: video
        hostPath:
          path: /dev/video0
          type: File